{
 "title": "Apache Solr query performance",
 "tags": [ "apache-solr-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(solr_metrics_jvm_os_cpu_load{}, job)"
   },
   {
    "name": "solr_cluster",
    "label": "Solr cluster",
    "query": "label_values(solr_metrics_jvm_os_cpu_load{job=~\"$job\"}, solr_cluster)"
   },
   {
    "name": "base_url",
    "label": "Instance",
    "query": "label_values(solr_metrics_jvm_os_cpu_load{job=~\"$job\",solr_cluster=~\"$solr_cluster\"}, base_url)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "solr_collection",
    "label": "Collection",
    "query": "label_values(solr_metrics_core_errors_total{job=~\"$job\"}, collection)"
   },
   {
    "name": "solr_core",
    "label": "Core",
    "query": "label_values(solr_metrics_core_errors_total{job=~\"$job\"}, core)"
   }
  ]
 },
 "panels": [
  { "title": "Query load", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Update handlers / $__interval",
   "type": "timeseries",
   "description": "Counts the increase in document additions over the specified interval.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "\n  avg by (job,base_url,collection,core) (\n  increase(solr_metrics_core_update_handler_adds_total{job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\",collection=~\"$solr_collection\", core=~\"$solr_core\"}[$__interval:] offset -$__interval)\n)\n > 0",
     "legendFormat": "{{collection}} - {{core}}"
    }
   ]
  },
  {
   "title": "Core search and retrieval query load",
   "type": "timeseries",
   "description": "Measures the average rate of queries per second over a 5-minute period for core search and retrieval operations.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "\n  avg by (job,searchHandler,base_url,collection,core) (\n  solr_metrics_core_query_5minRate{searchHandler=~\"/select|/query|/get\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\",collection=~\"$solr_collection\", core=~\"$solr_core\"}\n)\n > 0",
     "legendFormat": "{{collection}} - {{core}} - {{searchHandler}}"
    }
   ]
  },
  {
   "title": "Specialized query load",
   "type": "timeseries",
   "description": "Measures the average rate of specialized queries per second over a 5-minute period.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "\n  avg by (job,searchHandler,base_url,collection,core) (\n  solr_metrics_core_query_5minRate{searchHandler=~\"/sql|/export|/stream\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\",collection=~\"$solr_collection\", core=~\"$solr_core\"}\n)\n > 0",
     "legendFormat": "{{collection}} - {{core}} - {{searchHandler}}"
    }
   ]
  },
  {
   "title": "Core search and retrieval 95p query latency",
   "type": "timeseries",
   "description": "Represents the 95th percentile latency for core search and retrieval queries.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "\n  avg by (job,searchHandler,base_url,collection,core) (\n  solr_metrics_core_query_p95_ms{searchHandler=~\"/select|/query|/get\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\",collection=~\"$solr_collection\", core=~\"$solr_core\"}\n)\n > 0",
     "legendFormat": "{{collection}} - {{core}} - {{searchHandler}}"
    }
   ]
  },
  {
   "title": "Specialized 95p query latency",
   "type": "timeseries",
   "description": "Displays the 993ith percentile latency for specialized query types.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "\n  avg by (job,searchHandler,base_url,collection,core) (\n  solr_metrics_core_query_p95_ms{searchHandler=~\"/sql|/export|/stream\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\",collection=~\"$solr_collection\", core=~\"$solr_core\"}\n)\n > 0",
     "legendFormat": "{{collection}} - {{core}} - {{searchHandler}}"
    }
   ]
  },
  {
   "title": "Core search and retrieval 99p query latency",
   "type": "timeseries",
   "description": "Represents the 99th percentile latency for core search and retrieval queries, measured in milliseconds.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "\n  avg by (job,searchHandler,base_url,collection,core) (\n  solr_metrics_core_query_p99_ms{searchHandler=~\"/select|/query|/get\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\",collection=~\"$solr_collection\", core=~\"$solr_core\"}\n)\n > 0",
     "legendFormat": "{{collection}} - {{core}} - {{searchHandler}}"
    }
   ]
  },
  {
   "title": "Specialized 99p query latency",
   "type": "timeseries",
   "description": "Displays the 99th percentile latency for specialized query types.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "\n  avg by (job,searchHandler,base_url,collection,core) (\n  solr_metrics_core_query_p99_ms{searchHandler=~\"/sql|/export|/stream\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\",collection=~\"$solr_collection\", core=~\"$solr_core\"}\n)\n > 0",
     "legendFormat": "{{collection}} - {{core}} - {{searchHandler}}"
    }
   ]
  },
  { "title": "Local queries", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 25 } },
  {
   "title": "Core search and retrieval local query load",
   "type": "timeseries",
   "description": "Indicates the average rate of local queries per second over a 5-minute period for core search and retrieval operations.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "\n  avg by (job,searchHandler,base_url,collection,core) (\n  solr_metrics_core_query_local_5minRate{searchHandler=~\"/select|/query|/get\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\",collection=~\"$solr_collection\", core=~\"$solr_core\"}\n)\n > 0",
     "legendFormat": "{{collection}} - {{core}} - {{searchHandler}}"
    }
   ]
  },
  {
   "title": "Specialized local query load",
   "type": "timeseries",
   "description": "Indicates the average rate of local specialized queries per second over a 5-minute period.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "\n  avg by (job,searchHandler,base_url,collection,core) (\n  solr_metrics_core_query_local_5minRate{searchHandler=~\"/sql|/export|/stream\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\",collection=~\"$solr_collection\", core=~\"$solr_core\"}\n)\n > 0",
     "legendFormat": "{{collection}} - {{core}} - {{searchHandler}}"
    }
   ]
  },
  {
   "title": "Core search and retrieval local p95 query latency",
   "type": "timeseries",
   "description": "Represents the 95th percentile latency for local core search and retrieval queries.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "\n  avg by (job,searchHandler,base_url,collection,core) (\n  solr_metrics_core_query_local_p95_ms{searchHandler=~\"/select|/query|/get\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\",collection=~\"$solr_collection\", core=~\"$solr_core\"}\n)\n > 0",
     "legendFormat": "{{collection}} - {{core}} - {{searchHandler}}"
    }
   ]
  },
  {
   "title": "Specialized local 95p query latency",
   "type": "timeseries",
   "description": "Shows the 95th percentile latency for specialized local queries.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "\n  avg by (job,searchHandler,base_url,collection,core) (\n  solr_metrics_core_query_local_p95_ms{searchHandler=~\"/sql|/export|/stream\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\",collection=~\"$solr_collection\", core=~\"$solr_core\"}\n)\n > 0",
     "legendFormat": "{{collection}} - {{core}} - {{searchHandler}}"
    }
   ]
  },
  {
   "title": "Core search and retrieval 99p local query latency",
   "type": "timeseries",
   "description": "Represents the 99th percentile latency for local core search and retrieval queries.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "\n  avg by (job,searchHandler,base_url,collection,core) (\n  solr_metrics_core_query_local_p99_ms{searchHandler=~\"/select|/query|/get\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\",collection=~\"$solr_collection\", core=~\"$solr_core\"}\n)\n > 0",
     "legendFormat": "{{collection}} - {{core}} - {{searchHandler}}"
    }
   ]
  },
  {
   "title": "Specialized local 99p query latency",
   "type": "timeseries",
   "description": "Shows the 99th percentile latency for specialized local queries.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "\n  avg by (job,searchHandler,base_url,collection,core) (\n  solr_metrics_core_query_local_p99_ms{searchHandler=~\"/sql|/export|/stream\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\",collection=~\"$solr_collection\", core=~\"$solr_core\"}\n)\n > 0",
     "legendFormat": "{{collection}} - {{core}} - {{searchHandler}}"
    }
   ]
  },
  { "title": "Cache metrics", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 44 } },
  {
   "title": "Cache evictions / $__interval",
   "type": "timeseries",
   "description": "Tracks the number of cache evictions.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "\n  avg by (job,type,base_url,collection,core) (\n  increase(solr_metrics_core_searcher_cache{type=~\"documentCache|filterCache|queryResultCache\", item=~\"evictions\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\",collection=~\"$solr_collection\", core=~\"$solr_core\"}[$__interval:] offset -$__interval)\n)\n > 0",
     "legendFormat": "{{collection}} - {{core}} - {{type}}"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "timeseries",
   "description": "The cache hit ratio for various cache activities.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "\n  avg by (job,type,base_url,collection,core) (\n  100 * solr_metrics_core_searcher_cache_ratio{type=~\"documentCache|filterCache|queryResultCache\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\",collection=~\"$solr_collection\", core=~\"$solr_core\"}\n)\n > 0",
     "legendFormat": "{{collection}} - {{core}} - {{type}}"
    }
   ]
  },
  { "title": "Timeouts", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 51 } },
  {
   "title": "Core timeouts / $__interval",
   "type": "timeseries",
   "description": "Tracks the increase in the number of query timeouts over the specified time interval.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job,base_url,collection,core) (\n  increase(solr_metrics_core_timeouts_total{job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\",collection=~\"$solr_collection\", core=~\"$solr_core\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{collection}} - {{core}}"
    }
   ]
  },
  {
   "title": "Node timeouts / $__interval",
   "type": "timeseries",
   "description": "Tracks the increase in node-level query timeouts over the specified interval.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job,base_url) (\n  increase(solr_metrics_node_timeouts_total{job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{base_url}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 58 } },
  {
   "title": "Query error rate",
   "type": "timeseries",
   "description": "Measures the rate of query errors over a 1-minute period.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "errors / min" } },
   "targets": [
    {
     "expr": "avg by (job,base_url,collection,core) (\n  solr_metrics_core_query_errors_1minRate{job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\",collection=~\"$solr_collection\", core=~\"$solr_core\"}\n)",
     "legendFormat": "{{collection}} - {{core}}"
    }
   ]
  },
  {
   "title": "Query client errors",
   "type": "timeseries",
   "description": "This metric represents the rate of client errors over a 1-minute period.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "errors / min" } },
   "targets": [
    {
     "expr": "avg by (job,base_url,collection,core) (\n  solr_metrics_core_query_client_errors_1minRate{job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\",collection=~\"$solr_collection\", core=~\"$solr_core\"}\n)",
     "legendFormat": "{{collection}} - {{core}}"
    }
   ]
  }
 ]
}