{
 "title": "OpenSearch Node Overview",
 "tags": [ "opensearch" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(opensearch_cluster_status{opensearch_cluster!=\"\"}, job)"
   },
   {
    "name": "opensearch_cluster",
    "label": "Opensearch_cluster",
    "query": "label_values(opensearch_cluster_status{opensearch_cluster!=\"\",job=~\"$job\"}, opensearch_cluster)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(opensearch_cluster_status{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"}, node)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Node Roles", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Roles timeline",
   "type": "status-history",
   "description": "OpenSearch node roles over time.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by (node, role) (max_over_time(opensearch_node_role_bool{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\", role=\"data\"}[1m]) == 1) * 2",
     "legendFormat": "{{ node }} / data"
    },
    {
     "expr": "max by (node, role) (max_over_time(opensearch_node_role_bool{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\", role=\"master\"}[1m]) == 1) * 3",
     "legendFormat": "{{ node }} / master"
    },
    {
     "expr": "max by (node, role) (max_over_time(opensearch_node_role_bool{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\", role=\"ingest\"}[1m]) == 1) * 4",
     "legendFormat": "{{ node }} / ingest"
    },
    {
     "expr": "max by (node, role) (max_over_time(opensearch_node_role_bool{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\", role=\"cluster_manager\"}[1m]) == 1) * 5",
     "legendFormat": "{{ node }} / cluster_manager"
    },
    {
     "expr": "max by (node, role) (max_over_time(opensearch_node_role_bool{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\", role=\"remote_cluster_client\"}[1m]) == 1) * 6",
     "legendFormat": "{{ node }} / remote_client"
    }
   ]
  },
  {
   "title": "Roles",
   "type": "table",
   "description": "OpenSearch node roles.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max by (job,opensearch_cluster, nodeid, role, primary_ip) (last_over_time(opensearch_node_role_bool{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"}[1d]))",
     "legendFormat": "{{node}}: Node role bool last seen"
    }
   ]
  },
  { "title": "Node health", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 17 } },
  {
   "title": "Node CPU usage",
   "type": "timeseries",
   "description": "CPU usage percentage of the node's Operating System.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "opensearch_os_cpu_percent{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "timeseries",
   "description": "Memory usage percentage of the node for the Operating System and OpenSearch",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "opensearch_os_mem_used_percent{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node I/O",
   "type": "timeseries",
   "description": "Node file system read and write data.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (job,opensearch_cluster,node) (rate(opensearch_fs_io_total_read_bytes{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}} - read"
    },
    {
     "expr": "sum by (job,opensearch_cluster,node) (rate(opensearch_fs_io_total_write_bytes{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}} - write"
    }
   ]
  },
  {
   "title": "Node open connections",
   "type": "timeseries",
   "description": "Number of open connections for the selected node.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "sum by (job,opensearch_cluster,node) (opensearch_transport_server_open_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node disk usage",
   "type": "timeseries",
   "description": "Disk usage percentage of the selected node.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (100 * opensearch_fs_path_free_bytes{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"} / clamp_min(opensearch_fs_path_total_bytes{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"}, 1))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node memory swap",
   "type": "timeseries",
   "description": "Percentage of swap space used by OpenSearch and the Operating System on the selected node.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * opensearch_os_swap_used_bytes{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"} / clamp_min((opensearch_os_swap_used_bytes{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"} + opensearch_os_swap_free_bytes{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"}), 1)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node network traffic",
   "type": "timeseries",
   "description": "Network traffic on the node's Operating System.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (job,opensearch_cluster,node) (rate(opensearch_transport_rx_bytes_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"}[$__rate_interval])) * 8",
     "legendFormat": "{{node}} - received"
    },
    {
     "expr": "sum by (job,opensearch_cluster,node) (rate(opensearch_transport_tx_bytes_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"}[$__rate_interval])) * 8",
     "legendFormat": "{{node}} - sent"
    }
   ]
  },
  {
   "title": "Circuit breakers",
   "type": "timeseries",
   "description": "Circuit breakers tripped on the selected node by type",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "trips" } },
   "targets": [
    {
     "expr": "sum by (name, job,opensearch_cluster,node) (increase(opensearch_circuitbreaker_tripped_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"}[$__interval:]))",
     "legendFormat": "{{node}} - {{ name }}"
    }
   ]
  },
  { "title": "Node JVM", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 34 } },
  {
   "title": "JVM heap used vs committed",
   "type": "timeseries",
   "description": "JVM heap memory usage vs committed.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job,opensearch_cluster) (opensearch_jvm_mem_heap_used_bytes{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"})",
     "legendFormat": "{{node}}: JVM heap used"
    },
    {
     "expr": "sum by (job,opensearch_cluster) (opensearch_jvm_mem_heap_committed_bytes{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"})",
     "legendFormat": "{{node}}: JVM heap committed"
    }
   ]
  },
  {
   "title": "JVM non-heap used vs committed",
   "type": "timeseries",
   "description": "JVM non-heap memory usage vs committed.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job,opensearch_cluster) (opensearch_jvm_mem_nonheap_used_bytes{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"})",
     "legendFormat": "{{node}}: JVM non-heap used"
    },
    {
     "expr": "sum by (job,opensearch_cluster) (opensearch_jvm_mem_nonheap_committed_bytes{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"})",
     "legendFormat": "{{node}}: JVM non-heap committed"
    }
   ]
  },
  {
   "title": "JVM threads",
   "type": "timeseries",
   "description": "JVM thread count.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "threads" } },
   "targets": [
    {
     "expr": "sum by (job,opensearch_cluster) (opensearch_jvm_threads_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"})",
     "legendFormat": "{{node}}: JVM threads"
    }
   ]
  },
  {
   "title": "JVM buffer pools",
   "type": "timeseries",
   "description": "JVM buffer pool usage.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job,opensearch_cluster, bufferpool) (opensearch_jvm_bufferpool_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"})",
     "legendFormat": "{{ bufferpool }}"
    }
   ]
  },
  {
   "title": "JVM uptime",
   "type": "timeseries",
   "description": "JVM uptime in seconds.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job,opensearch_cluster) (opensearch_jvm_uptime_seconds{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"})",
     "legendFormat": "{{node}}: JVM uptime"
    }
   ]
  },
  {
   "title": "JVM garbage collections",
   "type": "timeseries",
   "description": "JVM garbage collection count.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "collections" } },
   "targets": [
    {
     "expr": "sum by (job,opensearch_cluster) (increase(opensearch_jvm_gc_collection_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"}[$__interval:]))",
     "legendFormat": "{{node}}: JVM GC collections"
    }
   ]
  },
  {
   "title": "JVM garbage collection time",
   "type": "timeseries",
   "description": "JVM garbage collection time in milliseconds.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (job,opensearch_cluster) (increase(opensearch_jvm_gc_collection_time_seconds{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"}[$__interval:]))",
     "legendFormat": "{{node}}: JVM GC time"
    }
   ]
  },
  {
   "title": "JVM buffer pool usage",
   "type": "timeseries",
   "description": "JVM buffer pool usage by pool.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "100 * (sum by (job,opensearch_cluster, bufferpool) (opensearch_jvm_bufferpool_used_bytes{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"})) / clamp_min((sum by (job, bufferpool, cluster) (opensearch_jvm_bufferpool_total_capacity_bytes{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"})),1)",
     "legendFormat": "{{ bufferpool }}"
    }
   ]
  },
  { "title": "Thread pools", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 51 } },
  {
   "title": "Thread pool threads",
   "type": "timeseries",
   "description": "Thread pool thread count.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "threads" } },
   "targets": [
    {
     "expr": "sum by (job,opensearch_cluster) ((opensearch_threadpool_threads_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"}))",
     "legendFormat": "{{node}}: Threadpool threads"
    }
   ]
  },
  {
   "title": "Thread pool tasks",
   "type": "timeseries",
   "description": "Thread pool task count.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "tasks" } },
   "targets": [
    {
     "expr": "sum by (job,opensearch_cluster) (opensearch_threadpool_tasks_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"})",
     "legendFormat": "{{node}}: Threadpool tasks"
    }
   ]
  }
 ]
}