{
 "title": "OpenSearch Cluster Overview",
 "tags": [ "opensearch" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(opensearch_cluster_status{opensearch_cluster!=\"\"}, job)"
   },
   {
    "name": "opensearch_cluster",
    "label": "Opensearch_cluster",
    "query": "label_values(opensearch_cluster_status{opensearch_cluster!=\"\",job=~\"$job\"}, opensearch_cluster)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(opensearch_cluster_status{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"}, node)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Cluster status",
   "type": "stat",
   "description": "The overall health and availability of the OpenSearch cluster.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (job,opensearch_cluster) (\n  opensearch_cluster_status{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"}\n)",
     "legendFormat": "{{opensearch_cluster}}"
    }
   ]
  },
  {
   "title": "Node count",
   "type": "stat",
   "description": "The number of running nodes across the OpenSearch cluster.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (job,opensearch_cluster) (\n  opensearch_cluster_nodes_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"}\n)",
     "legendFormat": "{{opensearch_cluster}}"
    }
   ]
  },
  {
   "title": "Data node count",
   "type": "stat",
   "description": "The number of data nodes in the OpenSearch cluster.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (job,opensearch_cluster) (\n  opensearch_cluster_datanodes_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"}\n)",
     "legendFormat": "{{opensearch_cluster}}"
    }
   ]
  },
  {
   "title": "Shard count",
   "type": "stat",
   "description": "The number of shards in the OpenSearch cluster across all indices.",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  max by (job,opensearch_cluster,type) (\n  opensearch_cluster_shards_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"}\n)\n)",
     "legendFormat": "{{opensearch_cluster}}"
    }
   ]
  },
  {
   "title": "Active shards %",
   "type": "stat",
   "description": "Percent of active shards across the OpenSearch cluster.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (job,opensearch_cluster) (\n  opensearch_cluster_shards_active_percent{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"}\n)",
     "legendFormat": "{{opensearch_cluster}}"
    }
   ]
  },
  { "title": "Node Roles", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 7 } },
  {
   "title": "Roles",
   "type": "table",
   "description": "OpenSearch node roles.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by (job,opensearch_cluster, nodeid, role, primary_ip) (last_over_time(opensearch_node_role_bool{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\"}[1d]))",
     "legendFormat": "{{node}}: Node role bool last seen"
    }
   ]
  },
  {
   "title": "Roles timeline",
   "type": "status-history",
   "description": "OpenSearch node roles over time.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by (node, role) (max_over_time(opensearch_node_role_bool{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\", role=\"data\"}[1m]) == 1) * 2",
     "legendFormat": "{{ node }} / data"
    },
    {
     "expr": "max by (node, role) (max_over_time(opensearch_node_role_bool{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\", role=\"master\"}[1m]) == 1) * 3",
     "legendFormat": "{{ node }} / master"
    },
    {
     "expr": "max by (node, role) (max_over_time(opensearch_node_role_bool{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\", role=\"ingest\"}[1m]) == 1) * 4",
     "legendFormat": "{{ node }} / ingest"
    },
    {
     "expr": "max by (node, role) (max_over_time(opensearch_node_role_bool{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\", role=\"cluster_manager\"}[1m]) == 1) * 5",
     "legendFormat": "{{ node }} / cluster_manager"
    },
    {
     "expr": "max by (node, role) (max_over_time(opensearch_node_role_bool{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\",node=~\"$node\", role=\"remote_cluster_client\"}[1m]) == 1) * 6",
     "legendFormat": "{{ node }} / remote_client"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 24 } },
  {
   "title": "Top nodes by CPU usage",
   "type": "bargauge",
   "description": "Top nodes by OS CPU usage across the OpenSearch cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(\n  topk(10, sort_desc(sum by(job,opensearch_cluster,node) (opensearch_os_cpu_percent{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"})))\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Breakers tripped",
   "type": "bargauge",
   "description": "The total count of circuit breakers tripped across the OpenSearch cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "trips" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job,opensearch_cluster) (\n  increase(opensearch_circuitbreaker_tripped_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Shard status",
   "type": "bargauge",
   "description": "Shard status counts across the OpenSearch cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "shards" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (job,opensearch_cluster,type) (\n  opensearch_cluster_shards_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"}\n)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Storage and Tasks", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 33 } },
  {
   "title": "Top nodes by disk usage",
   "type": "bargauge",
   "description": "Top nodes by disk usage across the OpenSearch cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sort_desc((100 * (sum by(job,opensearch_cluster,node) (opensearch_fs_path_total_bytes{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"})- sum by(job,opensearch_cluster,node) (opensearch_fs_path_free_bytes{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"})) / sum by(job,opensearch_cluster,node) (opensearch_fs_path_total_bytes{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"}))))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Total documents",
   "type": "timeseries",
   "description": "The total count of documents indexed across the OpenSearch cluster.",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "documents" } },
   "targets": [
    {
     "expr": "avg by (job,opensearch_cluster) (\n  opensearch_indices_indexing_index_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"}\n)",
     "legendFormat": "{{opensearch_cluster}}"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "timeseries",
   "description": "The number of tasks waiting to be executed across the OpenSearch cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "tasks" } },
   "targets": [
    {
     "expr": "avg by (job,opensearch_cluster) (\n  opensearch_cluster_pending_tasks_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"}\n)",
     "legendFormat": "{{opensearch_cluster}}"
    }
   ]
  },
  {
   "title": "Store size",
   "type": "timeseries",
   "description": "The total size of the store across the OpenSearch cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job,opensearch_cluster) (\n  opensearch_indices_store_size_bytes{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"}\n)",
     "legendFormat": "{{opensearch_cluster}}"
    }
   ]
  },
  {
   "title": "Max task wait time",
   "type": "timeseries",
   "description": "The max wait time for tasks to be executed across the OpenSearch cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (job,opensearch_cluster) (\n  opensearch_cluster_task_max_waiting_time_seconds{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"}\n)",
     "legendFormat": "{{opensearch_cluster}}"
    }
   ]
  },
  { "title": "Search Performance", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 50 } },
  {
   "title": "Top indices by request rate",
   "type": "timeseries",
   "description": "Top indices by combined fetch, query, and scroll request rate across the OpenSearch cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(avg by(index, job,opensearch_cluster) (\n  opensearch_index_search_fetch_current_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\", context=\"total\"} + \n  opensearch_index_search_query_current_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\", context=\"total\"} + \n  opensearch_index_search_scroll_current_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\", context=\"total\"}\n)))\n",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Top indices by request latency",
   "type": "timeseries",
   "description": "Top indices by combined fetch, query, and scroll latency across the OpenSearch cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(sum by(index, job,opensearch_cluster) ((increase(opensearch_index_search_fetch_time_seconds{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\", context=\"total\"}[$__interval:])\n+increase(opensearch_index_search_query_time_seconds{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\", context=\"total\"}[$__interval:])\n+increase(opensearch_index_search_scroll_time_seconds{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\", context=\"total\"}[$__interval:]))\n/ clamp_min(increase(opensearch_index_search_fetch_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\", context=\"total\"}[$__interval:])\n+increase(opensearch_index_search_query_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\", context=\"total\"}[$__interval:])\n+increase(opensearch_index_search_scroll_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\", context=\"total\"}[$__interval:]), 1))))\n",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Top indices by combined cache hit ratio",
   "type": "timeseries",
   "description": "Top indices by cache hit ratio for the combined request and query cache across the OpenSearch cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(avg by(index, job,opensearch_cluster) (\n  100 * (opensearch_index_requestcache_hit_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\", context=\"total\"} + \n  opensearch_index_querycache_hit_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\", context=\"total\"}) / \n  clamp_min((opensearch_index_requestcache_hit_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\", context=\"total\"} + \n  opensearch_index_querycache_hit_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\", context=\"total\"} + \n  opensearch_index_requestcache_miss_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\", context=\"total\"} + \n  opensearch_index_querycache_miss_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\", context=\"total\"}), 1\n  ))))",
     "legendFormat": "{{index}}"
    }
   ]
  },
  { "title": "Ingest Performance", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 59 } },
  {
   "title": "Top nodes by ingest rate",
   "type": "timeseries",
   "description": "Top nodes by rate of ingest across the OpenSearch cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10, sum by(job,opensearch_cluster,node) (rate(opensearch_ingest_total_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"}[$__rate_interval])))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Top nodes by ingest latency",
   "type": "timeseries",
   "description": "Top nodes by ingestion latency across the OpenSearch cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, sum by(job,opensearch_cluster,node) (increase(opensearch_ingest_total_time_seconds{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"}[$__interval:]) / clamp_min(increase(opensearch_ingest_total_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"}[$__interval:]), 1)))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Top nodes by ingest errors",
   "type": "timeseries",
   "description": "Top nodes by ingestion failures across the OpenSearch cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "errors" } },
   "targets": [
    {
     "expr": "topk(10, sum by(job,opensearch_cluster,node) (increase(opensearch_ingest_total_failed_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"}[$__interval:])))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Indexing Performance", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 68 } },
  {
   "title": "Top indices by index rate",
   "type": "timeseries",
   "description": "Top indices by rate of document indexing across the OpenSearch cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "documents/s" } },
   "targets": [
    {
     "expr": "topk(10, avg by(index, job,opensearch_cluster) (opensearch_index_indexing_index_current_number{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"}))",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Top indices by index latency",
   "type": "timeseries",
   "description": "Top indices by indexing latency across the OpenSearch cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, avg by(index, job,opensearch_cluster) (increase(opensearch_index_indexing_index_time_seconds{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\", context=\"total\"}[$__interval:]) / clamp_min(increase(opensearch_index_indexing_index_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\", context=\"total\"}[$__interval:]), 1)))",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Top indices by index failures",
   "type": "timeseries",
   "description": "Top indices by index document failures across the OpenSearch cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "failures" } },
   "targets": [
    {
     "expr": "topk(10, avg by(index, job,opensearch_cluster) (increase(opensearch_index_indexing_index_failed_count{opensearch_cluster!=\"\",job=~\"$job\",opensearch_cluster=~\"$opensearch_cluster\"}[$__interval:])))",
     "legendFormat": "{{index}}"
    }
   ]
  }
 ]
}